# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy

## Importing

In [3]:
import numpy as np #instead of np we can write anything, np is standard

## Numpy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list) # now this is an array , like a 1D matrix, all mathematical operations are possible

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] 
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix) #this is a matrix or a 2-D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
my_matrix2 = [[[1,2], [3,4]], [[2,5], [9,7]], [[4,5],[1,4]]]
np.array(my_matrix2)

array([[[1, 2],
        [3, 4]],

       [[2, 5],
        [9, 7]],

       [[4, 5],
        [1, 4]]])

In [88]:
my_matrix3 = [[1,2,3,2], [2,3,4,5], [7,8,9,6] , [2,4,5,6]]
np.array(my_matrix3)

array([[1, 2, 3, 2],
       [2, 3, 4, 5],
       [7, 8, 9, 6],
       [2, 4, 5, 6]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5,25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [10]:
np.arange(0, 11, 2) #(start, end, space)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(1)

array([1.])

In [91]:
np.zeros((2,3,5)) #(amt, row, col)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [92]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### linspace
Return evenly spaced numbers over a specified interval. the spaces are linear

In [17]:
np.linspace(0,10,3) #(start , end , no of points)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

## eye

Creates an identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [21]:
np.random.rand(2)

array([0.16727343, 0.63589535])

In [22]:
np.random.rand(5,5) #this is a 2D array

array([[0.17930117, 0.6009172 , 0.78877276, 0.20761123, 0.32587472],
       [0.6248433 , 0.08860903, 0.56371122, 0.8974119 , 0.9921485 ],
       [0.34566597, 0.7705865 , 0.93181759, 0.11167388, 0.35247012],
       [0.45897719, 0.66551291, 0.15324784, 0.49562607, 0.21365845],
       [0.25972106, 0.4654074 , 0.26416816, 0.56836083, 0.29971068]])

In [23]:
np.random.rand(25) #this is a linear array of 25 elements

array([2.36966734e-01, 2.95168811e-01, 1.66161776e-01, 5.31510453e-01,
       3.07384708e-01, 5.00902391e-01, 6.00822059e-01, 9.17281200e-01,
       1.18472590e-02, 6.63861594e-01, 6.79215660e-01, 7.34442830e-01,
       1.43110380e-01, 8.41071139e-01, 7.33471975e-04, 9.03739806e-02,
       8.70439073e-01, 2.20612855e-01, 8.19048104e-01, 4.05704831e-01,
       8.58720035e-01, 5.09661234e-01, 4.42322504e-01, 1.85719328e-01,
       3.49060493e-01])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

The standard normal dist. is created around zero

In [24]:
np.random.randn(2)

array([-1.25482364,  1.78519521])

In [25]:
np.random.randn(5,5)

array([[-0.92618434,  0.63894296,  1.12176455,  0.63121342,  0.32916493],
       [ 0.19078694,  1.18372422,  0.98301792,  1.4452996 ,  0.60585614],
       [-1.244934  , -0.74641554, -0.92418394, -2.14057347,  0.31236619],
       [-0.34219671,  3.06915749,  2.10196984,  0.1530719 ,  1.08886696],
       [ 0.38169484, -0.97492247,  0.18648762, -0.18104491, -0.08500078]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [26]:
np.random.randint(1,100)

76

In [27]:
np.random.randint(1,100,10)  #(start , end, no of points)

array([32, 79, 46, 37, 67,  3, 81, 95, 47, 40])

## Array Attributes and Methods


In [28]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr

array([38, 39,  9, 14, 16, 12, 27,  8, 32, 26])

## Reshape
Returns an array containing the same data with a new shape.

In [31]:
arr.reshape(5,5) #converting 25*1 1-d array into 5*5 2d array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr2 = np.arange(16)

In [33]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
arr2.reshape(4,4)  #converting 16*1 1-d array into 4*4 2d array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
arr2.reshape(2,2,2,2) #converting 16*1 1-d array into 2*2*2*2 4-d array

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [36]:
ranarr

array([38, 39,  9, 14, 16, 12, 27,  8, 32, 26])

In [37]:
ranarr.max()

39

In [38]:
ranarr.argmax()

1

In [39]:
ranarr.min()

8

In [40]:
ranarr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [41]:
arr.shape 

(25,)

In [42]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
arr.reshape(1,25).shape

(1, 25)

In [44]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.reshape(25,1).shape

(25, 1)

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(5,5).shape

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [48]:
arr.data #gives the data location

In [49]:
arr.dtype #gives the data type

dtype('int64')

In [50]:
arr2.dtype

dtype('int64')

In [51]:
list2 = ['a', 'b' , 'c']

In [52]:
arr3 = np.array(list2)

In [53]:
arr3.dtype

dtype('<U1')

# NumPy Indexing and Selection

 selecting elements or groups of elements from an array.

In [54]:
#creating sample array
arr4 = np.arange(0,11)

In [55]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [56]:
arr4[8]

8

In [57]:
arr4[1:5]

array([1, 2, 3, 4])

In [58]:
arr4[0:5]

array([0, 1, 2, 3, 4])

In [59]:
arr4[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr4[:7]

array([0, 1, 2, 3, 4, 5, 6])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [61]:
#we can change a value in a given range
arr4[0:5] = 100

arr4

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
slice_of_arr = arr4[0:6] #(start : end)

In [63]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [64]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
arr4 #the changes also occour in the orignal array, no copies of array are made

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
#to get a copy, meed to be explicit
arr_copy = arr4.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [67]:
arr_2d =np.array(([5,10,15], [20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[1]

array([20, 25, 30])

In [69]:
arr_2d[0]

array([ 5, 10, 15])

In [70]:
arr_2d[1][0]

20

In [71]:
arr_2d[1,0] #this is same as above

20

### 2D array slicing

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[:2,1:] #all rows before 2 , and all cols after 1 and also 1

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d[2]

array([35, 40, 45])

In [75]:
arr_2d[2, :]

array([35, 40, 45])

In [76]:
arr_2d[ :,1]

array([10, 25, 40])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [77]:
arr2d = np.zeros((10,10))

In [78]:
arr2d.shape

(10, 10)

In [98]:
arr_length = arr2d.shape[1]

In [99]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:

for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [101]:
arr2d[[2,4,6,8,9]] #this is fancy indexing

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [102]:
arr2d[[6,5,2,0]] #order does not matter

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Selection

 use of brackets for selection based off of comparison operators.

In [103]:
arr5 = np.arange(1,11)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr5 > 5 #gives a boolean array 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [105]:
bool_arr = arr>7

In [106]:
bool_arr

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [107]:
arr[bool_arr]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [108]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [109]:
x = 8
arr[arr>x]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [110]:
arr6 = np.arange(0,20)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
arr6 + arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [112]:
arr7 = np.arange(120,140)

In [113]:
arr6 + arr7 #the dimentions should be same

array([120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144,
       146, 148, 150, 152, 154, 156, 158])

In [114]:
arr6 * arr7

array([   0,  121,  244,  369,  496,  625,  756,  889, 1024, 1161, 1300,
       1441, 1584, 1729, 1876, 2025, 2176, 2329, 2484, 2641])

In [115]:
arr6 - arr7

array([-120, -120, -120, -120, -120, -120, -120, -120, -120, -120, -120,
       -120, -120, -120, -120, -120, -120, -120, -120, -120])

In [116]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr6/arr6

/var/folders/hl/hf60khhn7ll1g11lwbjr00sw0000gn/T/ipykernel_77267/3781836516.py:3: RuntimeWarning: invalid value encountered in divide
  arr6/arr6


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [117]:
1/arr6

/var/folders/hl/hf60khhn7ll1g11lwbjr00sw0000gn/T/ipykernel_77267/3180675830.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr6


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [118]:
arr6 ** 4

array([     0,      1,     16,     81,    256,    625,   1296,   2401,
         4096,   6561,  10000,  14641,  20736,  28561,  38416,  50625,
        65536,  83521, 104976, 130321])

In [119]:
arr6 ** arr7

array([                   0,                    1,                    0,
        4137309267128563259,                    0,   592528690091790037,
                          0, -7819604518968614473,                    0,
        7103118512662025225,                    0, -3910812743174723789,
                          0, -3172606404390435747,                    0,
         278851996148032367,                    0,  1476716623258430609,
                          0, -8179174654339325141])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [120]:
np.sqrt(arr6)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [121]:
np.exp(arr6)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [122]:
np.sin(arr6)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [123]:
np.cos(arr6)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [125]:
np.log(arr6)

/var/folders/hl/hf60khhn7ll1g11lwbjr00sw0000gn/T/ipykernel_77267/3307335837.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr6)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [126]:
np.arctan(arr7)

array([1.56246319, 1.56253205, 1.56259979, 1.56266642, 1.56273199,
       1.5627965 , 1.56285999, 1.56292247, 1.56298399, 1.56304454,
       1.56310417, 1.56316289, 1.56322071, 1.56327767, 1.56333378,
       1.56338905, 1.56344352, 1.56349719, 1.56355008, 1.56360221])

## ------------ ** ------------------------------- ** -----------------